import { RuleTester } from "@typescript-eslint/rule-tester";
import * as vitest from "vitest";

// TODO: move to setup before tests
RuleTester.afterAll = vitest.afterAll;
RuleTester.it = vitest.it;
RuleTester.itOnly = vitest.it.only;
RuleTester.describe = vitest.describe;

export const ruleTester = new RuleTester({
  languageOptions: {
    parserOptions: {
      projectService: {
        // default test file generated by ruletester, see https://typescript-eslint.io/packages/rule-tester/#type-aware-testing
        allowDefaultProject: ["file.ts"],
      },
    },
  },
});
