name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 11.25.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install --frozen-lockfile

      - name: Lint (plugin)
        run: pnpm --filter eslint-plugin-pulumi lint

      - name: Test (plugin)
        run: pnpm --filter eslint-plugin-pulumi test

      - name: Build (plugin)
        run: pnpm --filter eslint-plugin-pulumi build

      - name: Lint (test-playground)
        # TODO: improve this
        run: |
          pnpm --filter test-playground lint || true
