name: Release

on:
  push:
    branches: [main]
    # semantic-release will detect tags automatically
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance, see https://docs.npmjs.com/trusted-publishers
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11.25.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          cache: pnpm
          node-version: 24 # required for trusted publishing, node 22 is not working
          # node-version: lts/* # use this when node 24 is LTS

      - run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm --filter eslint-plugin-pulumi build

      - name: Verify provenance attestations and registry signatures
        # pnpm doesn't support it yet: https://github.com/pnpm/pnpm/issues/7909
        run: npm audit signatures

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
