name: Release

on:
  push:
    branches: [main]
    # semantic-release will detect tags automatically
    tags:
      - "v*.*.*"

# required for trusted publishing to NPM, see https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: latest

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          cache: pnpm
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm --filter eslint-plugin-pulumi build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
