name: Release

on:
  push:
    branches: [main]
    # semantic-release will detect tags automatically
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance, see https://docs.npmjs.com/trusted-publishers
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: latest

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install --frozen-lockfile

      - name: Build plugin
        run: pnpm --filter eslint-plugin-pulumi build

      - name: Verify provenance attestations and registry signatures
        # pnpm doesn't support it yet: https://github.com/pnpm/pnpm/issues/7909
        run: npm audit signatures

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx semantic-release
